### ISSUE TITLE
Допрацювання по оплаті інвойсів

### ISSUE THREAD

**Issue by Siusarna** [zonzujiro/korchivnyky-dashboard#20]
1. Можливість обрати звідки сплачуємо (accumulated чи otherSourcesAccumulated) 
2. При виборі банки в розділі "Що по банці" додати: пункти "витрачено" і "залишилося"
3. Після збереження оплати нічого не відбувається (закривається попап, але інфа в самому інвойсі не оновлюється, треба оновити сторінку

**Comment by zonzujiro** [comment]
> При виборі банки в розділі "Що по банці" додати: пункти "витрачено" і "залишилося"

@Siusarna WDYM? Current amount is already there. You want to know how much money was spent from this jar from within a dialog?

**Comment by Siusarna** [comment]
@zonzujiro This is not the current amount. This value shows how much money was raised during the fundraising campaign. 

> додати: пункти "витрачено" і "залишилося"
I mean to show the spent value and left over (value = accumulated - spent)

**Comment by zonzujiro** [comment]
![image](https://github.com/zonzujiro/korchivnyky-dashboard/assets/2997359/0bbef98d-f353-469c-93ac-28561b5253e2)

Done
